/**
 * Editor schema for the Easy Cover Styler Card visual editor.
 * One entry per top-level panel; each field maps to a card config key.
 * Field types: group | switch | select | number | text | chips | multi | entities
 *            | color | scale | slider | entityCombo | order.
 * `group` is a heading/divider inside a panel (no key).
 * `nested` (chips) writes into an object key (e.g. auto_filter.exclude).
 * `when(editor)` conditionally shows a field.
 */
import {DIVIDER_GRADIENT_PATTERNS} from './dividers.js';

export function buildSchema(C) {
  const GRAD_PATTERNS = DIVIDER_GRADIENT_PATTERNS.map((p, i) => [String(i), p.name]);
  const dividersOn = (ed) => !!ed._value(C.CONFIG_SHOW_COVER_DIVIDERS);
  const dividerGrad = (ed) => dividersOn(ed) && !!ed._value(C.CONFIG_DIVIDER_GRADIENT);
  const STATES = [
    C.SHUTTER_STATE_OPENING, C.SHUTTER_STATE_OPEN, C.SHUTTER_STATE_CLOSED,
    C.SHUTTER_STATE_CLOSING, C.SHUTTER_STATE_PARTIAL_OPEN,
  ];
  const TB = [[C.TOP, 'Top'], [C.BOTTOM, 'Bottom']];
  const SIDE = [['before', 'Left / before'], ['after', 'Right / after'], ['top', 'Top'], ['bottom', 'Bottom']];
  const ORIENT = [['auto', 'Auto (follow side)'], ['row', 'Horizontal row'], ['column', 'Vertical column']];
  const WEIGHTS = [['', 'Default'], ['normal', 'Normal'], ['500', 'Medium'], ['600', 'Semibold'], ['bold', 'Bold']];
  const isAreas = (ed) => !!ed._value(C.CONFIG_SHOW_AREA_SELECTOR) || ed._value(C.CONFIG_LAYOUT) === C.LAYOUT_AREAS;
  const isModern = (ed) => ed._value(C.CONFIG_COVER_VISUAL) === 'modern';
  const isImageVis = (ed) => !isModern(ed);
  const cleanOn = (ed) => !!ed._value(C.CONFIG_CLEAN_NAMES);
  const presetsOn = (ed) => !!ed._value(C.CONFIG_SHOW_PARTIAL_OPEN_BUTTONS);
  const valuesStyle = (ed) => presetsOn(ed) && ed._value(C.CONFIG_PARTIAL_BUTTONS_STYLE) === C.PARTIAL_STYLE_VALUES;

  return [
    {
      id: 'layout',
      icon: 'mdi:view-grid-plus-outline',
      title: 'Panel Layout',
      hint: 'Card structure — cover-panel orientation/wrapping, the area selector and the group panel.',
      fields: [
        {type: 'group', label: 'Cover Panels'},
        {key: C.CONFIG_ORIENTATION, label: 'Orientation', type: 'select',
          options: [['vertical', 'Vertical'], ['horizontal', 'Horizontal']],
          hint: 'How the cover panels stack — independent of the area selector.'},
        {key: C.CONFIG_COVERS_WRAP_MODE, label: 'Covers wrapping', type: 'select',
          options: [['scroll', 'Single line (scroll)'], ['wrap', 'Auto-wrap'], ['grid', 'Fixed columns']], when: isAreas},
        {key: C.CONFIG_COVERS_COLUMNS, label: 'Covers per row', type: 'slider', min: 1, max: 10, step: 1,
          when: (ed) => isAreas(ed) && ed._value(C.CONFIG_COVERS_WRAP_MODE) === 'grid'},
        {type: 'group', label: 'Collapse Toggle', when: isAreas},
        {key: C.CONFIG_COVERS_COLLAPSIBLE, label: 'Allow Collapsing The Covers', type: 'switch', when: isAreas},
        {key: C.CONFIG_COVERS_START_COLLAPSED, label: 'Start Collapsed', type: 'switch',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {key: C.CONFIG_COLLAPSE_SHOW_COUNT, label: 'Show Cover Count On Toggle', type: 'switch',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {key: C.CONFIG_COLLAPSE_LABEL, label: 'Collapse Toggle Label', type: 'text', placeholder: 'covers',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {key: C.CONFIG_COLLAPSE_ICON, label: 'Toggle Icon (Blank = Chevron)', type: 'text', placeholder: 'mdi:chevron-down',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {key: C.CONFIG_COLLAPSE_ICON_SIZE, label: 'Toggle Icon Size', type: 'slider', min: 0, max: 48, step: 1, unit: 'px', zeroLabel: 'Default',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {key: C.CONFIG_COLLAPSE_ICON_COLOR, label: 'Toggle Icon Color', type: 'color', defaultLabel: 'Inherit',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_COVERS_COLLAPSIBLE)},
        {type: 'group', label: 'Area Selector Panel'},
        {key: C.CONFIG_SHOW_AREA_SELECTOR, label: 'Show area selector', type: 'switch',
          hint: 'Adds the Area/Label button menu (works with either orientation). Needs Areas or Labels set in Entity Filters.'},
        {key: C.CONFIG_AREA_MENU_INLINE, label: 'Inline with cover panels', type: 'switch', when: isAreas},
        {key: C.CONFIG_AREA_BUTTONS_WRAP_MODE, label: 'Button rows', type: 'select',
          options: [['nowrap', 'Single row (scroll)'], ['wrap', 'Auto-wrap rows'], ['grid', 'Fixed columns']], when: isAreas},
        {key: C.CONFIG_AREA_BUTTONS_COLUMNS, label: 'Button columns', type: 'slider', min: 1, max: 8, step: 1,
          when: (ed) => isAreas(ed) && ed._value(C.CONFIG_AREA_BUTTONS_WRAP_MODE) === 'grid'},
        {key: C.CONFIG_AREA_BUTTON_WRAP, label: 'Wrap text inside buttons', type: 'switch', when: isAreas},
        {type: 'group', label: 'Group Panel', when: isAreas},
        {key: C.CONFIG_GROUP_INLINE, label: 'Inline with cover panels', type: 'switch', when: isAreas,
          hint: 'When both this and the Area Selector inline are off, the group sits beside the Area Selector panel (row 1).'},
        {key: C.CONFIG_GROUP_STICKY, label: 'Keep group panel fixed while scrolling', type: 'switch', when: isAreas},
      ],
    },
    {
      id: 'card',
      icon: 'mdi:palette-outline',
      title: 'Appearance',
      hint: 'Card title/preset, area menu style, group control, and name cleanup.',
      fields: [
        {type: 'group', label: 'Card'},
        {key: C.CONFIG_PASSIVE_MODE, label: 'Design Mode', type: 'switch',
          hint: 'Enable this to edit the design without sending cover commands.'},
        {key: C.CONFIG_TITLE, label: 'Title', type: 'text'},
        {type: 'group', label: 'Area Selector Panel', when: isAreas},
        {key: C.CONFIG_AREA_BUTTON_STYLE, label: 'Area button style', type: 'buttonStyle', when: isAreas,
          hint: 'Uses the shared Button Styles library (below) — or a built-in.'},
        {type: 'group', label: 'Group Control', when: isAreas},
        {key: C.CONFIG_SHOW_ALL_CONTROL, label: 'Show group control', type: 'switch', when: isAreas},
        {key: C.CONFIG_GROUP_NAME_FROM_AREA, label: 'Use the selected area name', type: 'switch',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_SHOW_ALL_CONTROL),
          hint: 'Group control shows the active area button\'s name instead of a fixed name.'},
        {key: C.CONFIG_ALL_LABEL, label: 'Group control name', type: 'text',
          when: (ed) => isAreas(ed) && !!ed._value(C.CONFIG_SHOW_ALL_CONTROL) && !ed._value(C.CONFIG_GROUP_NAME_FROM_AREA)},
        {type: 'group', label: 'Entity Name Cleaner'},
        {key: C.CONFIG_NAME_STRIP_AREA, label: 'Remove Room Name From Labels', type: 'switch',
          hint: 'Strips the cover\'s Area/room name out of the displayed label (on by default).'},
        {key: C.CONFIG_CLEAN_NAMES, label: 'Clean Up Names', type: 'switch'},
        {key: C.CONFIG_NAME_REMOVE, label: 'Remove Words / Substrings', type: 'chips', placeholder: 'e.g. Cover, Shade…', when: cleanOn},
        {key: C.CONFIG_NAME_CAPITALIZE, label: 'Capitalize Each Word', type: 'switch', when: cleanOn},
      ],
    },
    {
      id: 'filters',
      icon: 'mdi:filter-variant',
      title: 'Entity Filters',
      hint: 'Choose which covers the card shows — by Area/Label, and/or an explicit list.',
      fields: [
        {type: 'group', label: 'Auto-Generate'},
        {key: C.CONFIG_AREAS, label: 'Areas', type: 'chips', placeholder: 'Area name or id…'},
        {key: C.CONFIG_LABELS, label: 'Labels', type: 'chips', placeholder: 'Label name or id…'},
        {key: C.CONFIG_AUTO_FILTER, nested: 'device_class', label: 'Only these device classes', type: 'chips',
          placeholder: 'e.g. blind, shade…', hint: 'Leave empty to include all cover classes except the excluded ones.'},
        {key: C.CONFIG_AUTO_FILTER, nested: 'exclude', label: 'Exclude device classes', type: 'chips', placeholder: 'e.g. garage'},
        {type: 'group', label: 'Manual List'},
        {key: C.CONFIG_ENTITIES, label: 'Covers', type: 'entities'},
        {key: C.CONFIG_SHOW_GROUP_MEMBERS, label: 'Expand cover groups into members', type: 'switch'},
      ],
    },
    {
      id: 'positions',
      icon: 'mdi:arrow-all',
      title: 'Element Layout & Style',
      hint: 'One expandable subpanel per element — its show/hide (eye), where it sits, and its look (icons, colours, layout). How the controls behave lives in Controls Behavior.',
      fields: [
        {key: C.CONFIG_SHOW_WINDOW, label: 'Cover image / bar', type: 'eye'},
        {type: 'item', id: 'std', icon: 'mdi:arrow-up-down', label: 'Movement Control Buttons', eyeKey: C.CONFIG_SHOW_STANDARD_BUTTONS, fields: [
          {key: C.CONFIG_STANDARD_POSITION, label: 'Side', type: 'select', options: SIDE},
          {key: C.CONFIG_STANDARD_ORIENTATION, label: 'Layout', type: 'select', options: ORIENT},
          {key: C.CONFIG_BUTTONS_POSITION, label: 'Buttons Position (legacy auto)', type: 'select',
            options: [C.LEFT, C.RIGHT, C.TOP, C.BOTTOM, C.AUTO, C.AUTO_TL, C.AUTO_TR, C.AUTO_BL, C.AUTO_BR]},
          {key: C.CONFIG_CONTROL_ICON_COLOR, label: 'Icon Color', type: 'color', defaultLabel: 'Inherit',
            hint: 'Color for up/stop/down/favorite-position and tilt icons.'},
          {key: C.CONFIG_ICON_UP, label: 'Up Icon', type: 'text', placeholder: 'mdi:arrow-up'},
          {key: C.CONFIG_ICON_STOP, label: 'Stop Icon', type: 'text', placeholder: 'mdi:stop'},
          {key: C.CONFIG_ICON_DOWN, label: 'Down Icon', type: 'text', placeholder: 'mdi:arrow-down'},
          {key: C.CONFIG_ICON_PARTIAL, label: 'Favorite Position Icon', type: 'text', placeholder: 'mdi:star-circle'},
          {key: C.CONFIG_CONTROLS_BUTTON_PAD, label: 'Button Padding (0 = tight)', type: 'slider', min: 0, max: 24, step: 1, unit: 'px'},
          {key: C.CONFIG_CONTROLS_BUTTON_MARGIN, label: 'Space Around Button Group', type: 'slider', min: 0, max: 40, step: 1, unit: 'px'},
        ]},
        {type: 'item', id: 'slider', icon: 'mdi:tune-vertical', label: 'Open/close slider', eyeKey: C.CONFIG_SHOW_OPEN_CLOSE_SLIDER, fields: [
          {key: C.CONFIG_SLIDER_POSITION, label: 'Side', type: 'select', options: SIDE},
        ]},
        {type: 'item', id: 'tilt', icon: 'mdi:angle-acute', label: 'Tilt controls', eyeKey: C.CONFIG_SHOW_TILT_BUTTONS, fields: [
          {key: C.CONFIG_TILT_POSITION, label: 'Side', type: 'select', options: SIDE},
          {key: C.CONFIG_SHOW_TILT_SLIDER, label: 'Show Tilt Slider Too', type: 'switch'},
          {key: C.CONFIG_ICON_TILT_UP, label: 'Tilt-Up Icon', type: 'text', placeholder: 'mdi:arrow-top-right'},
          {key: C.CONFIG_ICON_TILT_DOWN, label: 'Tilt-Down Icon', type: 'text', placeholder: 'mdi:arrow-bottom-left'},
        ]},
        {type: 'item', id: 'presets', icon: 'mdi:format-list-numbered', label: 'Preset buttons', eyeKey: C.CONFIG_SHOW_PARTIAL_OPEN_BUTTONS, fields: [
          {key: C.CONFIG_PRESETS_POSITION, label: 'Side', type: 'select', options: SIDE},
          {key: C.CONFIG_PRESETS_ORIENTATION, label: 'Layout', type: 'select', options: ORIENT},
          {key: C.CONFIG_PARTIAL_BUTTONS_STYLE, label: 'Preset Button Style', type: 'select',
            options: [[C.PARTIAL_STYLE_ICONS, 'Icons'], [C.PARTIAL_STYLE_VALUES, 'Values (20%, 50%…)']]},
          {key: C.CONFIG_PCT_ICON_COLOR, label: 'Preset Icon Color', type: 'color', defaultLabel: 'Inherit',
            when: (ed) => ed._value(C.CONFIG_PARTIAL_BUTTONS_STYLE) !== C.PARTIAL_STYLE_VALUES},
          {key: C.CONFIG_PCT_BUTTON_STYLE, label: 'Button Style (Library)', type: 'buttonStyle', when: valuesStyle,
            hint: 'Optional — use a shared Button Style. Overrides the colors below.'},
          {key: C.CONFIG_PCT_BUTTON_BG, label: 'Button Background', type: 'color', defaultLabel: 'Theme', allowTransparent: true, when: valuesStyle},
          {key: C.CONFIG_PCT_BUTTON_BORDER, label: 'Button Border', type: 'color', defaultLabel: 'Theme', allowTransparent: true, transparentLabel: 'None', when: valuesStyle},
          {key: C.CONFIG_PCT_BUTTON_COLOR, label: 'Button Text Color', type: 'color', defaultLabel: 'Theme', when: valuesStyle},
          {key: C.CONFIG_PCT_BUTTON_WEIGHT, label: 'Button Text Weight', type: 'select', options: WEIGHTS, when: valuesStyle},
          {key: C.CONFIG_PCT_BUTTON_SIZE, label: 'Button Text Size', type: 'slider', min: 0, max: 30, step: 1, unit: 'px', zeroLabel: 'Default', when: valuesStyle},
        ]},
        {type: 'item', id: 'name', icon: 'mdi:format-title', label: 'Name', eyeKey: C.CONFIG_SHOW_NAME, fields: [
          {key: C.CONFIG_NAME_POSITION, label: 'Position', type: 'select', options: TB},
        ]},
        {type: 'item', id: 'posval', icon: 'mdi:numeric', label: 'Position Value (on the panel)', eyeKey: C.CONFIG_PANEL_POS_SHOW, fields: [
          {key: C.CONFIG_POSITION_PLACEMENT, label: 'Placement', type: 'select',
            options: [['top', 'Top of image'], ['bottom', 'Bottom of image'], ['left', 'Left of image'], ['right', 'Right of image'],
              ['on-handle', 'On the handle'],
              ['at-handle-left', 'At handle — left'], ['at-handle-right', 'At handle — right'],
              ['at-handle-above', 'At handle — above'], ['at-handle-below', 'At handle — below']],
            hint: 'An independent %-readout around the image/bar. On/at-handle tracks the shade edge. The header readout is separate (under Header).'},
          {key: C.CONFIG_PANEL_POS_END, label: 'Open/Closed text', type: 'select',
            options: [['handle', 'On the handle (with %)'], ['center', 'Centre of bar'], ['above', 'Above the bar'], ['below', 'Below the bar']],
            when: (ed) => ed._value(C.CONFIG_POSITION_PLACEMENT) === 'on-handle',
            hint: 'Where the end-state Open/Closed text sits when the readout is on the handle. The numeric % stays on the handle.'},
          {key: C.CONFIG_PANEL_POS_SIZE, label: 'Size', type: 'slider', min: 0, max: 40, step: 1, unit: 'px', zeroLabel: 'Default'},
          {key: C.CONFIG_PANEL_POS_WEIGHT, label: 'Weight', type: 'select', options: WEIGHTS},
          {key: C.CONFIG_PANEL_POS_COLOR, label: 'Color', type: 'color', defaultLabel: 'Inherit'},
        ]},
        {type: 'item', id: 'battery', icon: 'mdi:battery-70', label: 'Battery', eyeKey: C.CONFIG_SHOW_BATTERY, fields: [
          {key: C.CONFIG_BATTERY_POSITION, label: 'Position', type: 'select',
            options: [['', 'Follow default'], [C.TOP, 'Top'], [C.BOTTOM, 'Bottom'], [C.LEFT, 'Left of image'], [C.RIGHT, 'Right of image']]},
          {key: C.CONFIG_BATTERY_ALIGN, label: 'Align (top/bottom)', type: 'select', options: [['left', 'Left'], ['center', 'Center'], ['right', 'Right']]},
          {key: C.CONFIG_ICONS_POSITION, label: 'Default row (battery + signal)', type: 'select', options: TB},
        ]},
        {type: 'item', id: 'signal', icon: 'mdi:wifi', label: 'Signal', eyeKey: C.CONFIG_SHOW_SIGNAL, fields: [
          {key: C.CONFIG_SIGNAL_POSITION, label: 'Position', type: 'select',
            options: [['', 'Follow default'], [C.TOP, 'Top'], [C.BOTTOM, 'Bottom'], [C.LEFT, 'Left of image'], [C.RIGHT, 'Right of image']]},
          {key: C.CONFIG_SIGNAL_ALIGN, label: 'Align (top/bottom)', type: 'select', options: [['left', 'Left'], ['center', 'Center'], ['right', 'Right']]},
        ]},
      ],
    },
    {
      id: 'header',
      icon: 'mdi:card-text-outline',
      title: 'Header',
      hint: 'Name, position/status readout and battery/signal — text styles, sources, and header row layout. (Show/hide + placement are in Element Layout & Style.)',
      fields: [
        {type: 'note', label: 'Show/hide and where each item sits are in the “Element Layout & Style” panel. This panel is text styles, sources, and the header-row layout.'},
        {type: 'group', label: 'Name'},
        {key: C.CONFIG_NAME_TEXT_SIZE, label: 'Name size', type: 'slider', min: 0, max: 60, step: 1, unit: 'px', zeroLabel: 'Default'},
        {key: C.CONFIG_NAME_TEXT_WEIGHT, label: 'Name weight', type: 'select', options: WEIGHTS},
        {key: C.CONFIG_NAME_TEXT_COLOR, label: 'Name color', type: 'color', defaultLabel: 'Inherit'},

        {type: 'group', label: 'Position Value (Header)'},
        {key: C.CONFIG_SHOW_OPENING, label: 'Show in header', type: 'switch'},
        {key: C.CONFIG_OPENING_POSITION, label: 'Row', type: 'select', options: TB},
        {key: C.CONFIG_ALWAYS_PCT, label: 'Always show percentage', type: 'switch'},
        {key: C.CONFIG_POSITION_TEXT_SIZE, label: 'Size', type: 'slider', min: 0, max: 40, step: 1, unit: 'px', zeroLabel: 'Default'},
        {key: C.CONFIG_POSITION_TEXT_WEIGHT, label: 'Weight', type: 'select', options: WEIGHTS},
        {key: C.CONFIG_POSITION_TEXT_COLOR, label: 'Color', type: 'color', defaultLabel: 'Inherit'},
        {key: C.CONFIG_POSITION_BACKGROUND, label: 'Highlight box', type: 'switch',
          hint: 'Off (default) shows plain text; on restores the shaded box.'},

        {type: 'group', label: 'Battery'},
        {key: C.CONFIG_BATTERY_ENTITY_ID, label: 'Battery source', type: 'entityCombo'},
        {type: 'group', label: 'Signal'},
        {key: C.CONFIG_SIGNAL_ENTITY_ID, label: 'Signal source', type: 'entityCombo'},

        {type: 'group', label: 'Header Row Layout'},
        {key: C.CONFIG_INLINE_HEADER, label: 'Name + position on same line', type: 'switch'},
        {key: C.CONFIG_HEADER_ORDER, label: 'Header order', type: 'select', options: [['name', 'Name first'], ['position', 'Position first']]},
        {key: C.CONFIG_HEADER_ALIGN, label: 'Header alignment', type: 'select', options: [['left', 'Left'], ['center', 'Center'], ['right', 'Right']]},
        {key: C.CONFIG_HEADER_GAP, label: 'Header item spacing', type: 'slider', min: 0, max: 40, step: 1, unit: 'px'},
      ],
    },
    {
      id: 'dividers',
      icon: 'mdi:minus',
      title: 'Cover Dividers',
      hint: 'Draw a divider between individual covers. Full styling suite (matches the other cards).',
      fields: [
        {key: C.CONFIG_SHOW_COVER_DIVIDERS, label: 'Show dividers between covers', type: 'switch'},
        {type: 'group', label: 'Line', when: dividersOn},
        {key: C.CONFIG_DIVIDER_HIDE_LINE, label: 'Hide line (content only)', type: 'switch', when: dividersOn},
        {key: C.CONFIG_DIVIDER_STYLE, label: 'Line style', type: 'select',
          options: [['solid', 'Solid'], ['dashed', 'Dashed'], ['dotted', 'Dotted']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_COLOR, label: 'Line color', type: 'color', defaultLabel: 'Theme divider', when: dividersOn},
        {key: C.CONFIG_DIVIDER_THICKNESS, label: 'Thickness', type: 'slider', min: 1, max: 12, step: 1, unit: 'px', when: dividersOn},
        {key: C.CONFIG_DIVIDER_LENGTH, label: 'Length', type: 'slider', min: 5, max: 100, step: 1, unit: '%', when: dividersOn},
        {key: C.CONFIG_DIVIDER_JUSTIFY, label: 'Line position', type: 'select',
          options: [['left', 'Left'], ['center', 'Center'], ['right', 'Right']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_PAD, label: 'Padding', type: 'slider', min: 0, max: 40, step: 1, unit: 'px', when: dividersOn},
        {type: 'group', label: 'Gradient', when: dividersOn},
        {key: C.CONFIG_DIVIDER_GRADIENT, label: 'Gradient line', type: 'switch', when: dividersOn},
        {key: C.CONFIG_DIVIDER_GRADIENT_PATTERN, label: 'Preset pattern', type: 'select', options: GRAD_PATTERNS, when: dividerGrad},
        {key: C.CONFIG_DIVIDER_STOPS, label: 'Custom stops', type: 'gradientStops', when: dividerGrad,
          hint: 'Override the preset with your own stops (add ≥2). Empty = use the preset above.'},
        {key: C.CONFIG_DIVIDER_MIRROR_CENTER, label: 'Mirror around centered content', type: 'switch', when: dividerGrad},
        {type: 'group', label: 'Text', when: dividersOn},
        {key: C.CONFIG_DIVIDER_LABEL, label: 'Label', type: 'text', when: dividersOn},
        {key: C.CONFIG_DIVIDER_TEXT_POSITION, label: 'Content position', type: 'select',
          options: [['above', 'Above'], ['on', 'On the line'], ['below', 'Below']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_CONTENT_JUSTIFY, label: 'Content alignment', type: 'select',
          options: [['left', 'Left'], ['center', 'Center'], ['right', 'Right']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_INDENT, label: 'Indent', type: 'slider', min: 0, max: 200, step: 2, unit: 'px', when: dividersOn},
        {key: C.CONFIG_DIVIDER_TEXT_SIZE, label: 'Text size', type: 'slider', min: 8, max: 40, step: 1, unit: 'px', when: dividersOn},
        {key: C.CONFIG_DIVIDER_TEXT_WEIGHT, label: 'Text weight', type: 'select', options: WEIGHTS, when: dividersOn},
        {key: C.CONFIG_DIVIDER_TEXT_COLOR_MODE, label: 'Text color', type: 'select',
          options: [['line', 'Match line'], ['theme', 'Theme'], ['fixed', 'Custom']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_TEXT_COLOR, label: 'Text color value', type: 'color', defaultLabel: 'None',
          when: (ed) => dividersOn(ed) && ['theme', 'fixed'].includes(ed._value(C.CONFIG_DIVIDER_TEXT_COLOR_MODE))},
        {type: 'group', label: 'Icon', when: dividersOn},
        {key: C.CONFIG_DIVIDER_ICON, label: 'Icon (mdi:…)', type: 'text', when: dividersOn},
        {key: C.CONFIG_DIVIDER_ICON_SIZE, label: 'Icon size', type: 'slider', min: 0, max: 48, step: 1, unit: 'px', zeroLabel: 'Auto', when: dividersOn},
        {key: C.CONFIG_DIVIDER_ICON_COLOR_MODE, label: 'Icon color', type: 'select',
          options: [['text', 'Match text'], ['theme', 'Theme'], ['fixed', 'Custom']], when: dividersOn},
        {key: C.CONFIG_DIVIDER_ICON_COLOR, label: 'Icon color value', type: 'color', defaultLabel: 'None',
          when: (ed) => dividersOn(ed) && ['theme', 'fixed'].includes(ed._value(C.CONFIG_DIVIDER_ICON_COLOR_MODE))},
      ],
    },
    {
      id: 'appearance',
      icon: 'mdi:image-outline',
      title: 'Styling',
      hint: 'Pick a cover type to fill the images, then override any slot. Each slot takes a filename or a CSS color.',
      fields: [
        {type: 'group', label: 'Visual Style'},
        {key: C.CONFIG_COVER_VISUAL, label: 'Cover Visual', type: 'select',
          options: [['image', 'Classic (window / shutter image)'], ['modern', 'Modern bar (slider)']]},
        {key: C.CONFIG_MODERN_STYLE, label: 'Modern Style', type: 'modernStyle', when: isModern,
          hint: 'Built-in look, or a style from your Slider Styles library. Custom colours/gradients: edit an entry in the library (or set `modern_style` inline in YAML).'},
        {type: 'group', label: 'Preset'},
        {key: C.CONFIG_SHUTTER_PRESET, label: 'Preset - Applied Default', type: 'select', options: [...C.ESC_TYPES, C.ESC_COMPACT],
          hint: 'The default look/behaviour for every cover. Any slot in Preset Overrides that you set wins over this. Per-area/entity presets use the same list.'},
        {type: 'group', label: 'Preset Overrides', when: isImageVis},
        {key: C.CONFIG_WINDOW_IMAGE, label: 'Window Image', type: 'imageSelect', options: C.BUNDLED_WINDOW_IMAGES, when: isImageVis},
        {key: C.CONFIG_VIEW_IMAGE, label: 'View Image / Color', type: 'imageSelect', options: C.BUNDLED_VIEW_IMAGES, when: isImageVis},
        {key: C.CONFIG_SHUTTER_SLAT_IMAGE, label: 'Slat Image / Color', type: 'imageSelect', options: C.BUNDLED_SLAT_IMAGES, when: isImageVis},
        {key: C.CONFIG_SHUTTER_BOTTOM_IMAGE, label: 'Bottom-Bar Image / Color', type: 'imageSelect', options: C.BUNDLED_BOTTOM_IMAGES, when: isImageVis},
        {key: C.CONFIG_ROTATE_SLATS_SHUTTER_IMAGE, label: 'Rotate Slat Image With Direction', type: 'switch', when: isImageVis},
        {key: C.CONFIG_STRETCH_EDGE_SHUTTER_IMAGE, label: 'Stretch Bottom Image', type: 'switch', when: isImageVis},
        {key: C.CONFIG_IMAGE_MAP, label: 'Images Base Path', type: 'text', when: isImageVis,
          hint: 'Folder that holds the image files (change only if you use custom images).'},
        {type: 'group', label: 'Per-Area & Per-Entity Presets'},
        {key: C.CONFIG_AREA_PRESETS, label: 'By Area', type: 'presetMap', kind: 'area',
          hint: 'Give every auto-collected cover in an area a cover-type preset (which carries its own images).'},
        {key: C.CONFIG_ENTITY_PRESETS, label: 'By Entity', type: 'presetMap', kind: 'entity',
          hint: 'Override a specific cover with a cover-type preset. Wins over the per-area preset.'},
      ],
    },
    {
      id: 'sizing',
      icon: 'mdi:resize',
      title: 'Scaling & Sizing',
      hint: 'Overall scaling, cover dimensions and spacing.',
      fields: [
        {type: 'group', label: 'Scaling'},
        {key: C.CONFIG_SCALE_TEXTS, label: 'Scale texts', type: 'scale'},
        {key: C.CONFIG_SCALE_BUTTONS, label: 'Scale buttons', type: 'scale'},
        {key: C.CONFIG_SCALE_ICONS, label: 'Scale icons', type: 'scale'},
        {type: 'group', label: 'Sizing'},
        {key: C.CONFIG_BASE_HEIGHT_PX, label: 'Base height', type: 'slider', min: 50, max: 400, step: 5, unit: 'px'},
        {key: C.CONFIG_BASE_WIDTH_PX, label: 'Base width', type: 'slider', min: 50, max: 400, step: 5, unit: 'px'},
        {key: C.CONFIG_RESIZE_HEIGHT_PCT, label: 'Resize height', type: 'slider', min: 20, max: 500, step: 5, unit: '%'},
        {key: C.CONFIG_RESIZE_WIDTH_PCT, label: 'Resize width', type: 'slider', min: 20, max: 500, step: 5, unit: '%'},
        {key: C.CONFIG_OFFSET_OPENED_PCT, label: 'Top offset', type: 'slider', min: 0, max: 100, step: 1, unit: '%'},
        {key: C.CONFIG_OFFSET_CLOSED_PCT, label: 'Bottom offset', type: 'slider', min: 0, max: 100, step: 1, unit: '%'},
        {key: C.CONFIG_OFFSET_IS_CLOSED_PCT, label: 'Treat as "closed" below', type: 'slider', min: 0, max: 100, step: 1, unit: '%'},
        {type: 'group', label: 'Cover Panel Padding'},
        {key: C.CONFIG_COVER_PAD_TOP, label: 'Padding top', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {key: C.CONFIG_COVER_PAD_RIGHT, label: 'Padding right', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {key: C.CONFIG_COVER_PAD_BOTTOM, label: 'Padding bottom', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {key: C.CONFIG_COVER_PAD_LEFT, label: 'Padding left', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {type: 'group', label: 'Padding Between Panel Sections'},
        {key: C.CONFIG_CONTROLS_GAP, label: 'Controls ↔ Image Gap', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {key: C.CONFIG_HEADER_IMAGE_GAP, label: 'Header ↔ Image Gap', type: 'slider', min: 0, max: 60, step: 1, unit: 'px'},
        {key: C.CONFIG_COVER_GAP, label: 'Add Padding, Group ↔ Individual Panels', type: 'slider', min: 0, max: 80, step: 1, unit: 'px'},
      ],
    },
    {
      id: 'behavior',
      icon: 'mdi:cog-outline',
      title: 'Controls Behavior',
      hint: 'How the controls behave — movement direction, limits, presets, invert options and per-state button hiding. Where each control sits and how it looks live in Element Layout & Style.',
      fields: [
        {type: 'group', label: 'Movement'},
        {key: C.CONFIG_CLOSING_DIRECTION, label: 'Closing Direction', type: 'select', options: [C.DOWN, C.LEFT, C.RIGHT]},
        {key: C.CONFIG_MODERN_TRAVEL, label: 'Travel Style', type: 'select', when: isModern,
          options: [['single', 'Single (one edge)'], ['center', 'Center-out (two panels)'], ['tdbu', 'Top-down / bottom-up']],
          hint: 'How the fill opens. Center-out splits from the middle. Top-down/bottom-up shows the band between two rails (needs a 2nd entity for the top rail).'},
        {key: C.CONFIG_MODERN_SECOND_ENTITY, label: 'Top-Rail Entity (TDBU)', type: 'text', placeholder: 'cover.…',
          when: (ed) => isModern(ed) && ed._value(C.CONFIG_MODERN_TRAVEL) === 'tdbu',
          hint: 'Top-down/bottom-up: put the card on the BOTTOM rail entity and set the TOP rail entity here (e.g. Motion Blinds exposes Top / Bottom / Combined covers — use Top). The band shows between the two rails\' current_position. Dragging currently moves the bottom rail; the top rail follows this entity.'},
        {type: 'group', label: 'Position Presets'},
        {key: C.CONFIG_POSITION_PRESETS, label: 'Preset Percentages', type: 'chips', placeholder: 'e.g. 50',
          hint: 'Used for the Values style. Empty = default set (100/75/50/25/10/0).', when: valuesStyle},
        {key: C.CONFIG_PARTIAL_CLOSE_PCT, label: 'Favorite Position %', type: 'slider', min: 0, max: 100, step: 1, unit: '%',
          hint: 'Adds a single one-tap button (in the Movement Control Buttons group) that sends the cover to this position. 0 hides it.'},
        {type: 'group', label: 'Invert'},
        {key: C.CONFIG_INVERT_PCT_UI, label: 'Invert percentage (UI)', type: 'switch'},
        {key: C.CONFIG_INVERT_PCT_COVER, label: 'Invert percentage (device)', type: 'switch'},
        {key: C.CONFIG_INVERT_OPEN_CLOSE_UI, label: 'Invert open/close (UI)', type: 'switch'},
        {key: C.CONFIG_INVERT_OPEN_CLOSE_COVER, label: 'Invert open/close (device)', type: 'switch'},
        {key: C.CONFIG_INVERT_PCT_TILT_UI, label: 'Invert tilt % (UI)', type: 'switch'},
        {key: C.CONFIG_INVERT_PCT_TILT_COVER, label: 'Invert tilt % (device)', type: 'switch'},
        {type: 'group', label: 'Tilt Angles'},
        {key: C.CONFIG_TILT_ANGLE_MIN, label: 'Tilt angle min', type: 'slider', min: 0, max: 360, step: 5, unit: '°'},
        {key: C.CONFIG_TILT_ANGLE_MAX, label: 'Tilt angle max', type: 'slider', min: 0, max: 360, step: 5, unit: '°'},
        {type: 'group', label: 'Movement Control Buttons'},
        {key: C.CONFIG_DISABLE_END_BUTTONS, label: 'Disable End Buttons At Limits', type: 'switch'},
        {key: C.CONFIG_BUTTON_OPENED_HIDE_STATES, label: 'Hide UP in states', type: 'multi', options: STATES},
        {key: C.CONFIG_BUTTON_STOP_HIDE_STATES, label: 'Hide STOP in states', type: 'multi', options: STATES},
        {key: C.CONFIG_BUTTON_CLOSED_HIDE_STATES, label: 'Hide DOWN in states', type: 'multi', options: STATES},
      ],
    },
  ];
}
